RestClients:
  intellix:
    UUID: a3fb2ba0-71ab-49a6-82fe-bb0c202b38bd
    Url: https://{host}/
    Icon: res:/webContent/logos/intellix.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    - com.axonivy.connector.intellix.connector.IntellixAuthFeature
    Properties:
      PATH.host: ${ivy.var.intellixConnector.host}
      UserName: ${ivy.var.intellixConnector.username}
      Password: ${ivy.var.intellixConnector.password}
      LogonUrl: ${ivy.var.intellixConnector.logonurl}
      HostId: notMyHost
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
